export const screenNames = {
  Map: 'Map',
  Profile: 'Profile',
  Posts: 'Posts',
  Settings: 'Settings',
  PostPreview: 'PostPreview',
  SignIn: 'SignIn',
  CreatePost: 'CreatePost',
  EditPost: 'EditPost',
  PostsList: 'PostsList',
  PaymentMethod: 'PaymentMethod',
  Preview: 'Preview',
  ProductsList: 'ProductsList',
  Summary: 'Summary',
};
